
# Syntax highlighting
markdown:            kramdown
# highlighter:         pygments
highlighter:         rouge

# Permalinks
permalink:           /:title
# relative_permalinks: true

# Setup
timezone:            Europe/Berlin # eg. Asia/Kathmandu
locale:              en_us
name:				         UXperts
title:               UXperts
tagline:             'tagline'
description:         'A link library to all topics UX.'
url:                 https://thomas-ge.github.io/
# rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/hero/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Thomas Grikschas
  url:            	 http://thomas-the-ux.com/
  # facebook:          username
  twitter:           '@feierabendcrew'
  # google_plus:       username
  # linkedin:          username
  # dribbble:          username
  # pinterest:         username
  # kiva:              username

# fb_admins:           your facebook profile id
# fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
